"""Taint Tracking — data provenance and flow control.

Reference: OpenFang taint tracking with ZeroizingString.
Tracks where data originated and prevents untrusted data
from reaching sensitive operations without sanitization.
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from enum import Flag, auto
from typing import Any

_log = logging.getLogger(__name__)


class TaintLabel(Flag):
    """Labels indicating data origin/trust level."""
    CLEAN = 0
    USER_INPUT = auto()      # From user message
    LLM_OUTPUT = auto()      # Generated by LLM
    EXTERNAL_API = auto()    # From external service
    FILE_SYSTEM = auto()     # Read from disk
    NETWORK = auto()         # From network request
    UNTRUSTED = auto()       # Explicitly untrusted
    SANITIZED = auto()       # Has been sanitized


@dataclass
class TaintedValue:
    """A value with taint metadata."""
    value: Any
    labels: TaintLabel = TaintLabel.CLEAN
    source: str = ""
    timestamp: float = field(default_factory=time.time)
    sanitized_by: str | None = None

    @property
    def is_trusted(self) -> bool:
        """Check if value is safe for sensitive operations."""
        dangerous = (
            TaintLabel.USER_INPUT | TaintLabel.LLM_OUTPUT |
            TaintLabel.EXTERNAL_API | TaintLabel.UNTRUSTED
        )
        if self.labels & dangerous:
            return bool(self.labels & TaintLabel.SANITIZED)
        return True

    def sanitize(self, sanitizer: str) -> "TaintedValue":
        """Mark as sanitized."""
        return TaintedValue(
            value=self.value,
            labels=self.labels | TaintLabel.SANITIZED,
            source=self.source,
            timestamp=self.timestamp,
            sanitized_by=sanitizer,
        )


class TaintTracker:
    """Tracks taint labels across data flow.

    Used to ensure user input is sanitized before:
    - Shell execution
    - File path construction
    - SQL queries
    - Template rendering
    """

    def __init__(self) -> None:
        self._tracked: dict[str, TaintedValue] = {}
        self._violations: list[dict[str, Any]] = []

    def track(self, key: str, value: Any, labels: TaintLabel, source: str = "") -> TaintedValue:
        """Track a new tainted value."""
        tv = TaintedValue(value=value, labels=labels, source=source)
        self._tracked[key] = tv
        return tv

    def get(self, key: str) -> TaintedValue | None:
        return self._tracked.get(key)

    def check(self, key: str, required_trust: bool = True) -> bool:
        """Check if a tracked value meets trust requirements.

        Records a violation if untrusted data is used in a sensitive context.
        """
        tv = self._tracked.get(key)
        if tv is None:
            return True  # Untracked = assume OK (backwards compat)

        if required_trust and not tv.is_trusted:
            violation = {
                "key": key,
                "labels": str(tv.labels),
                "source": tv.source,
                "timestamp": time.time(),
            }
            self._violations.append(violation)
            _log.warning("Taint violation: untrusted data '%s' from '%s'", key, tv.source)
            return False
        return True

    def sanitize(self, key: str, sanitizer: str) -> bool:
        """Mark a tracked value as sanitized."""
        tv = self._tracked.get(key)
        if tv is None:
            return False
        self._tracked[key] = tv.sanitize(sanitizer)
        return True

    def clear(self, key: str) -> None:
        self._tracked.pop(key, None)

    def get_violations(self) -> list[dict[str, Any]]:
        return list(self._violations)

    def stats(self) -> dict[str, Any]:
        return {
            "tracked_values": len(self._tracked),
            "violations": len(self._violations),
            "untrusted_count": sum(
                1 for tv in self._tracked.values() if not tv.is_trusted
            ),
        }
